# Global application configuration (OmegaConf)
# Default values only; no environment interpolation or API keys included.

environment: dev
debug: true
log_level: INFO

llm:
  provider: ollama
  model_name: llama3
  base_url: null
  request_timeout: 60

search:
  provider: tavily
  bing_search_url: null
  searx_base_url: null
  max_results: 5
  search_depth: basic

vectorstore:
  persist_directory: data/vectorstore
  collection_prefix: genmentor
  embedding_model: text-embedding-3-small

rag:
  chunk_size: 1000
  num_search_results: 3
  num_retrieval_results: 5
  allow_parallel: true
  max_workers: 3

server:
  host: 127.0.0.1
  port: 5000
