# Hydra entrypoint config that composes the default application settings
defaults:
  - default
  - _self_

debug: true
log_level: DEBUG

llm:
  model_name: llama3

search:
  max_results: 5

rag:
  chunk_size: 1000

# Optionally, override server settings here
server:
  host: 127.0.0.1
  port: 5000
